#' Replace dirty addresses with cleaned addresses
#'
#' @description
#' Replace the dirty address values in `df$var` with the cleaned values in `df_src$var_src` generated by [clean_address()].
#'
#' @inheritSection pull_addresses Address validation workflow
#' @inheritSection pull_addresses Melissa Data
#'
#' @param df A dataframe of addresses.
#' @param var A variable name in `df` whose values will be replaced.
#' @param df_src A dataframe with the variable supplied in `var_src` that contains the replacement text.
#' @param var_src A variable name in `df_src` that contains the replacement text. Defaults to `replacement_text.`
#' @param row_id A unique row identifier variable in `df`. Defaults to `address_id`.
#'
#' @return A dataframe.
#' @export
#'
#' @importFrom magrittr %>%
#'
#' @family address processing functions
# @examples
#'
replace_values <- function(df, var, df_src, var_src = "replacement_text", row_id = "address_id") {
  if (!is.data.frame(df) | !is.data.frame(df_src)) {
    stop("`df` and `df_src` must be dataframes")
  }
  if (length(var) != 1 | length(var_src) != 1 | length(row_id) != 1) {
    stop("`var`, `var_src`, and `row_id` must have length of 1")
  }

  var_check(df, var = c(var, row_id))
  var_check(df_src, var = c(var_src, row_id))

  if (any(duplicated(df[[row_id]])) | any(duplicated(df_src[[row_id]]))) {
    stop("`row_id` is not a unique row identifier in `df` and/or `df_src`")
  }

  # Subset rows in `df` that match cleaned rows in `df_src`
  df_x <- df %>%
    dplyr::semi_join(df_src, by = row_id)

  # Subtract rows in `df` that match cleaned rows in `df_src`
  df_y <- df %>%
    dplyr::anti_join(df_src, by = row_id)

  # Replace values in `df_x$var` with replacement text in `df_src$var_src`
  df_x <- df_x %>%
    dplyr::select(-tidyselect::all_of(var)) %>%
    dplyr::left_join(
      df_src %>%
        dplyr::select(tidyselect::all_of(row_id), tidyselect::all_of(var_src)),
      by = row_id,
      relationship = "one-to-one"
    ) %>%
    dplyr::rename({{ var }} := {{ var_src }}) %>%
    dplyr::select(tidyselect::all_of(colnames(df)))

  # Join `df_x` and `df_y`
  df_xy <- df_y %>%
    dplyr::full_join(df_x, by = colnames(df))

  # Restore `df` to original row order
  df %>%
    dplyr::select(tidyselect::all_of(row_id)) %>%
    dplyr::left_join(df_xy, by = row_id)
}
