#' Replace dirty addresses with cleaned addresses
#'
#' Replace the dirty address values in `df$var` with the cleaned values in `df_src$var_src` generated by [clean_street_address()].
#'
#' @param df A dataframe of addresses.
#' @param var A variable name in `df` whose values will be replaced.
#' @param df_src A dataframe with the variable supplied in `var_src` that contains the replacement text.
#' @param var_src A variable name in `df_src` that contains the replacement text. Defaults to `replacement_text.`
#' @param row_id A unique row identifier variable in `df`. Defaults to `address_id`.
#'
#' @return A dataframe.
#' @export
#'
#' @importFrom magrittr %>%
#'
#' @family address processing functions
# @examples
#'
replace_values <- function(df, var, df_src, var_src = "replacement_text", row_id = "address_id") {
  var_check(df, var = c(var, row_id))
  var_check(df_src, var = c(var_src, row_id))

  if (anyDuplicated(df$row_id) > 0 | anyDuplicated(df_src$row_id) > 0) {
    stop("`row_id` values are not all unique in `df` and/or `df_src`")
  }

  # Subset rows in `df` that match cleaned rows in `df_src`
  df2 <- df %>%
    dplyr::semi_join(df_src, by = row_id)

  # Remove rows in `df` that match cleaned rows in `df_src`
  df <- df %>%
    dplyr::anti_join(df_src, by = row_id)

  # Replace values in `df2$var` with replacement text in `df_src$var_src`
  df2 <- df2 %>%
    dplyr::select(-tidyselect::all_of(var)) %>%
    dplyr::left_join(
      df_src %>%
        dplyr::select(tidyselect::all_of(row_id), tidyselect::all_of(var_src)),
      by = row_id,
      relationship = "one-to-one"
    ) %>%
    dplyr::rename({{ var }} := {{ var_src }}) %>%
    dplyr::select(tidyselect::all_of(colnames(df)))

  # df2[[var]] <- df_src[[var_src]]

  # Join modified rows from `df2` back to `df`
  df %>%
    dplyr::full_join(df2, by = colnames(df))
}
