#' Replace dirty addresses with cleaned addresses
#'
#' Replace the dirty address values in `df$var` with the cleaned values in `source$replacement_text` generated by [clean_values()].
#'
#' @param df A dataframe of addresses.
#' @param var A variable name in `df` whose values will be replaced.
#' @param id_var A variable name in `df` that serves as a unique row identifier.
#' @param source A dataframe with the variable `replacement_text`.
#'
#' @return A dataframe.
#' @export
#'
#' @family address processing functions
# @examples

replace_values <- function(df, var, id_var, source) {

  var_check(df, var = c(var, id_var))
  var_check(source, var = "replacement_text")

  # Separate rows in `df` that match cleaned rows in `source`
  df_sub <- df %>%
    semi_join(source, by = id_var)

  # Remove rows in `df` that match cleaned rows in `source`
  df <- df %>%
    anti_join(source, by = id_var)

  # Replace values in `df` with replacement text in `source`
  df_sub[[var]] <- source[["replacement_text"]]

  # Join cleaned rows back to `df`
  df %>%
    full_join(df_sub, by = colnames(df))

}
